Laboratorio3/Models/ErrorViewModel.cs
using System;

namespace Laboratorio3.Models
{
  public class ErrorViewModel
  {
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
  }
}

Laboratorio3/Models/MovieModel.cs
using System;

namespace Laboratorio3.Models
{
  public class MovieModel
  {

    public int Id { get; set; }
    public string Name { get; set; }
    public string Genre { get; set; }
    public DateTime ReleasedDate { get; set; }

  }
}

Laboratorio3/Models/SongModel.cs
using System;

namespace Laboratorio3.Models
{
  public class SongsModel
  {

    public string Name { get; set; }
    public string Author { get; set; }
    public string Genre { get; set; }
    public string Album { get; set; }
    public DateTime ReleasedDate { get; set; }
    public TimeSpan Duration { get; set; }

  }
}

Laboratorio3/Controllers/HomeController.cs
using Laboratorio3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Laboratorio3.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
      _logger = logger;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Privacy()
    {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

Laboratorio3/Controllers/MovieController.cs
using Laboratorio3.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Laboratorio3.Controllers
{
  public class MovieController : Controller
  {
    public IActionResult Index()
    {
      var movies = GetListOfMovies();
      ViewBag.MainTitle = "List of my favorite films";
      return View(movies);
    }

    private List<MovieModel> GetListOfMovies()
    {
      List<MovieModel> movies = new List<MovieModel>();
      movies.Add(new MovieModel { Id = 1, Name = "Dune", Genre = "Science Fiction", 
        ReleasedDate = new DateTime(2021, 10, 22) });
      movies.Add(new MovieModel { Id = 2, Name = "Spiderman: No Way Home", Genre = "Action/Adventure", 
        ReleasedDate = new DateTime(2021, 12, 17) });
      movies.Add(new MovieModel { Id = 3, Name = "Your Name", Genre = "Romance/Fantasy", 
        ReleasedDate = new DateTime(2016, 08, 26) });

      return movies;
    }
  }
}

Laboratorio3/Controllers/SongController.cs
using Laboratorio3.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Laboratorio3.Controllers
{
  public class SongsController : Controller
  {
    public IActionResult Index()
    {
      var songs = GetListOfSongs();
      ViewBag.MainTitle = "My favorite song";
      return View(songs);
    }

    private List<SongsModel> GetListOfSongs()
    {
      List<SongsModel> songs = new List<SongsModel>();
      songs.Add(new SongsModel { Name = "Close To You", Author = "Dayglow", Genre = "Alternative/Indie",
        Album = "Harmony House", ReleasedDate = new DateTime (2021, 01, 12), Duration = new TimeSpan(-00,3,15) });

      return songs;
    }
  }
}

Laboratorio3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Laboratorio3/Views/Movie/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model List<Laboratorio3.Models.MovieModel>;

@{
  ViewData["Title"] = "Movies";
}

<h1>@ViewBag.MainTitle</h1>

<div>
  <table class = "table">
    <thead>
      <tr>
        <th>Movie Title</th>
        <th>Gender</th>
        <th>Released Date</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
        <tr>
          <td>@item.Name</td>
          <td>@item.Genre</td>
          <td>@item.ReleasedDate</td>
        </tr>
      }
    </tbody>
  </table>
</div>

<div>
  <button>I am a button</button>
</div>

Laboratorio3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorio3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorio3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Songs" asp-action="Index">Songs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Laboratorio3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Laboratorio3/Views/Songs/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model List<Laboratorio3.Models.SongsModel>;

@{
  ViewData["Title"] = "Songs";
}

<h1>@ViewBag.MainTitle</h1><br><br><br>

<style>
  #Tipo {
    display:inline;
    position:absolute;
  }
</style>

<style>
  #Atributo {
    text-align:center;
  }
</style>

<body>
  <div>
    <div>
      <p id = "Tipo"><b>Name:</b></p> 
      <p id = "Atributo">@Model[0].Name</p>
      <hr/>
    </div>
    <br><br>
    <div>
      <p id = "Tipo"><b>Author:</b></p> 
      <p id = "Atributo">@Model[0].Author</p>
      <hr/>
    </div>
    <br><br>
    <div>
      <p id = "Tipo"><b>Genre:</b></p> 
      <p id = "Atributo">@Model[0].Genre</p>
      <hr/>
    </div>
    <br><br>
    <div>
      <p id = "Tipo"><b>Album:</b></p> 
      <p id = "Atributo">@Model[0].Album</p>
      <hr/>
    </div>
    <br><br>
    <div>
      <p id = "Tipo"><b>Released Date:</b></p> 
      <p id = "Atributo">@Model[0].ReleasedDate</p>
      <hr/>
    </div>
    <br><br>
    <div>
      <p id = "Tipo"><b>Duration:</b></p> 
      <p id = "Atributo">@Model[0].Duration</p>
    </div>
  </div>
</body>